<a href="https://colab.research.google.com/github/hisoonni/bigdata/blob/main/%EC%9E%91%EC%97%85%ED%98%95_2%EC%9C%A0%ED%98%95_%EB%B2%A0%EC%9D%B4%EC%8A%A4%EB%9D%BC%EC%9D%B8%EC%BD%94%EB%93%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [28]:
import pandas as pd
import numpy as np

In [29]:
train=pd.read_csv('/content/sample_data/train.csv')
test=pd.read_csv('/content/sample_data/test.csv')

In [30]:
train.head()

ID  Gender Ever_Married  Age Graduated  Profession  Work_Experience  \
0  462809    Male           No   22        No  Healthcare              1.0   
1  466315  Female          Yes   67       Yes    Engineer              1.0   
2  461735    Male          Yes   67       Yes      Lawyer              0.0   
3  461319    Male          Yes   56        No      Artist              0.0   
4  460156    Male           No   32       Yes  Healthcare              1.0   

  Spending_Score  Family_Size  Var_1  Segmentation  
0            Low          4.0  Cat_4             4  
1            Low          1.0  Cat_6             2  
2           High          2.0  Cat_6             2  
3        Average          2.0  Cat_6             3  
4            Low          3.0  Cat_6             3

In [31]:
test.head()

ID  Gender Ever_Married  Age Graduated  Profession  Work_Experience  \
0  458989  Female          Yes   36       Yes    Engineer              0.0   
1  458994    Male          Yes   37       Yes  Healthcare              8.0   
2  459000    Male          Yes   59        No   Executive             11.0   
3  459003    Male          Yes   47       Yes      Doctor              0.0   
4  459005    Male          Yes   61       Yes      Doctor              5.0   

  Spending_Score  Family_Size  Var_1  
0            Low          1.0  Cat_6  
1        Average          4.0  Cat_6  
2           High          2.0  Cat_6  
3           High          5.0  Cat_4  
4            Low          3.0  Cat_6

In [32]:
train=train.drop('ID',axis=1)

test=test.drop('ID',axis=1)

train_y=train['Segmentation']

#수치형 컬럼 분류 -> 스케일링 적용
col_num=['Age','Work_Experience','Family_Size']
#범주형 컬럼 분류 -> 원핫인코딩 적용
col_cat=['Gender','Ever_Married','Graduated','Profession','Spending_Score','Var_1']

In [33]:
train.head()

Gender Ever_Married  Age Graduated  Profession  Work_Experience  \
0    Male           No   22        No  Healthcare              1.0   
1  Female          Yes   67       Yes    Engineer              1.0   
2    Male          Yes   67       Yes      Lawyer              0.0   
3    Male          Yes   56        No      Artist              0.0   
4    Male           No   32       Yes  Healthcare              1.0   

  Spending_Score  Family_Size  Var_1  Segmentation  
0            Low          4.0  Cat_4             4  
1            Low          1.0  Cat_6             2  
2           High          2.0  Cat_6             2  
3        Average          2.0  Cat_6             3  
4            Low          3.0  Cat_6             3

In [34]:
from pandas import get_dummies
#범주형 자료는 원핫인코딩
train_encoding=pd.get_dummies(train[col_cat])

train_encoding.head()


Gender_Female  Gender_Male  Ever_Married_No  Ever_Married_Yes  \
0              0            1                1                 0   
1              1            0                0                 1   
2              0            1                0                 1   
3              0            1                0                 1   
4              0            1                1                 0   

   Graduated_No  Graduated_Yes  Profession_Artist  Profession_Doctor  \
0             1              0                  0                  0   
1             0              1                  0                  0   
2             0              1                  0                  0   
3             1              0                  1                  0   
4             0              1                  0                  0   

   Profession_Engineer  Profession_Entertainment  ...  Spending_Score_Average  \
0                    0                         0  ...                       0   
1                    1                         0  ...                       0   
2                    0                         0  ...                       0   
3                    0                         0  ...                       1   
4                    0                         0  ...                       0   

   Spending_Score_High  Spending_Score_Low  Var_1_Cat_1  Var_1_Cat_2  \
0                    0                   1            0            0   
1                    0                   1            0            0   
2                    1                   0            0            0   
3                    0                   0            0            0   
4                    0                   1            0            0   

   Var_1_Cat_3  Var_1_Cat_4  Var_1_Cat_5  Var_1_Cat_6  Var_1_Cat_7  
0            0            1            0            0            0  
1            0            0            0            1            0  
2            0            0            0            1            0  
3            0            0            0            1            0  
4            0            0            0            1            0  

[5 rows x 25 columns]

In [35]:
test_encoding=pd.get_dummies(test[col_cat])

test_encoding.head()

Gender_Female  Gender_Male  Ever_Married_No  Ever_Married_Yes  \
0              1            0                0                 1   
1              0            1                0                 1   
2              0            1                0                 1   
3              0            1                0                 1   
4              0            1                0                 1   

   Graduated_No  Graduated_Yes  Profession_Artist  Profession_Doctor  \
0             0              1                  0                  0   
1             0              1                  0                  0   
2             1              0                  0                  0   
3             0              1                  0                  1   
4             0              1                  0                  1   

   Profession_Engineer  Profession_Entertainment  ...  Spending_Score_Average  \
0                    1                         0  ...                       0   
1                    0                         0  ...                       1   
2                    0                         0  ...                       0   
3                    0                         0  ...                       0   
4                    0                         0  ...                       0   

   Spending_Score_High  Spending_Score_Low  Var_1_Cat_1  Var_1_Cat_2  \
0                    0                   1            0            0   
1                    0                   0            0            0   
2                    1                   0            0            0   
3                    1                   0            0            0   
4                    0                   1            0            0   

   Var_1_Cat_3  Var_1_Cat_4  Var_1_Cat_5  Var_1_Cat_6  Var_1_Cat_7  
0            0            0            0            1            0  
1            0            0            0            1            0  
2            0            0            0            1            0  
3            0            1            0            0            0  
4            0            0            0            1            0  

[5 rows x 25 columns]

In [36]:
train[col_num].head()

Age  Work_Experience  Family_Size
0   22              1.0          4.0
1   67              1.0          1.0
2   67              0.0          2.0
3   56              0.0          2.0
4   32              1.0          3.0

In [37]:
#수치형 자료 스케일링 적용
from sklearn.preprocessing import MinMaxScaler

scaler=MinMaxScaler()

scaler.fit(train[col_num])

train[col_num]=scaler.transform(train[col_num])

test[col_num]=scaler.transform(test[col_num])

train=pd.concat([train[col_num],train_encoding],axis=1)

In [38]:
train.head()

Age  Work_Experience  Family_Size  Gender_Female  Gender_Male  \
0  0.056338         0.071429        0.375              0            1   
1  0.690141         0.071429        0.000              1            0   
2  0.690141         0.000000        0.125              0            1   
3  0.535211         0.000000        0.125              0            1   
4  0.197183         0.071429        0.250              0            1   

   Ever_Married_No  Ever_Married_Yes  Graduated_No  Graduated_Yes  \
0                1                 0             1              0   
1                0                 1             0              1   
2                0                 1             0              1   
3                0                 1             1              0   
4                1                 0             0              1   

   Profession_Artist  ...  Spending_Score_Average  Spending_Score_High  \
0                  0  ...                       0                    0   
1                  0  ...                       0                    0   
2                  0  ...                       0                    1   
3                  1  ...                       1                    0   
4                  0  ...                       0                    0   

   Spending_Score_Low  Var_1_Cat_1  Var_1_Cat_2  Var_1_Cat_3  Var_1_Cat_4  \
0                   1            0            0            0            1   
1                   1            0            0            0            0   
2                   0            0            0            0            0   
3                   0            0            0            0            0   
4                   1            0            0            0            0   

   Var_1_Cat_5  Var_1_Cat_6  Var_1_Cat_7  
0            0            0            0  
1            0            1            0  
2            0            1            0  
3            0            1            0  
4            0            1            0  

[5 rows x 28 columns]

In [39]:
test=pd.concat([test[col_num],test_encoding],axis=1)

test.head()

Age  Work_Experience  Family_Size  Gender_Female  Gender_Male  \
0  0.253521         0.000000        0.000              1            0   
1  0.267606         0.571429        0.375              0            1   
2  0.577465         0.785714        0.125              0            1   
3  0.408451         0.000000        0.500              0            1   
4  0.605634         0.357143        0.250              0            1   

   Ever_Married_No  Ever_Married_Yes  Graduated_No  Graduated_Yes  \
0                0                 1             0              1   
1                0                 1             0              1   
2                0                 1             1              0   
3                0                 1             0              1   
4                0                 1             0              1   

   Profession_Artist  ...  Spending_Score_Average  Spending_Score_High  \
0                  0  ...                       0                    0   
1                  0  ...                       1                    0   
2                  0  ...                       0                    1   
3                  0  ...                       0                    1   
4                  0  ...                       0                    0   

   Spending_Score_Low  Var_1_Cat_1  Var_1_Cat_2  Var_1_Cat_3  Var_1_Cat_4  \
0                   1            0            0            0            0   
1                   0            0            0            0            0   
2                   0            0            0            0            0   
3                   0            0            0            0            1   
4                   1            0            0            0            0   

   Var_1_Cat_5  Var_1_Cat_6  Var_1_Cat_7  
0            0            1            0  
1            0            1            0  
2            0            1            0  
3            0            0            0  
4            0            1            0  

[5 rows x 28 columns]

In [40]:
# 데이터셋 분리
from sklearn.model_selection import train_test_split

X_tr, X_val, y_tr, y_val = train_test_split(train, train_y, test_size=0.3, random_state=42)

X_tr.head()

X_val.head()

y_tr.head()

y_val.head()

239     4
2272    3
6172    4
2575    1
5509    1
Name: Segmentation, dtype: int64

In [41]:
# 모델 생성 ( 랜더포레스트로 무조건 )
from sklearn.ensemble import RandomForestClassifier

rfc=RandomForestClassifier()

rfc.fit(X_tr, y_tr)

predict_y_tr=rfc.predict(X_tr)

predict_y_tr

array([1, 3, 4, ..., 3, 1, 4])

In [42]:
from sklearn.metrics import f1_score

f1_score(y_tr, predict_y_tr, average='macro')

0.9654742747397538

In [43]:
predict_y_val=rfc.predict(X_val)

predict_y_val

array([4, 1, 4, ..., 1, 1, 2])

In [44]:
f1_score(y_val, predict_y_val, average='macro')

predict_y_test=rfc.predict(test)

predict_y_test

array([2, 1, 3, ..., 2, 2, 4])

In [45]:
predict_testpd=pd.DataFrame(predict_y_test)

In [46]:
predict_testpd.to_csv('수험번호.csv', index=False)